# Generated by Django 2.1.4 on 2019-02-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190220_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
