# Generated by Django 2.1.4 on 2019-02-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190220_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
