# Generated by Django 2.1.4 on 2019-02-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20190216_0323'),
        ('posts', '0009_auto_20190221_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.FileField(blank=True, null=True, upload_to='Post')),
                ('content', models.TextField(max_length=2000)),
                ('link', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete='Uploaded By', to='User.Teacher')),
            ],
        ),
    ]
