# Generated by Django 2.1.4 on 2019-02-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_poststudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststudent',
            name='user',
            field=models.ForeignKey(default=1, on_delete='Uploaded By', to='User.Student'),
        ),
    ]
