# Generated by Django 2.1.4 on 2019-02-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190221_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststudent',
            name='user',
            field=models.CharField(default=1, max_length=100, verbose_name='Uploaded By'),
        ),
    ]
