# Generated by Django 2.1.4 on 2019-02-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20190221_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poststudent',
            options={'ordering': ['-timestamp', '-updated']},
        ),
    ]
