# Generated by Django 2.1.4 on 2019-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20190221_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststudent',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Uploaded By'),
        ),
    ]
