# Generated by Django 2.1.4 on 2019-02-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20190221_2139'),
        ('comments', '0002_auto_20190220_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete='Post', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Uploaded By'),
        ),
    ]
