# Generated by Django 2.1.4 on 2019-02-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0017_auto_20190221_2139'),
        ('comments', '0006_auto_20190222_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Uploaded By')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=True, to='comments.CommentStudent')),
                ('post', models.ForeignKey(default=1, on_delete='Post', to='posts.Post')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
