# Generated by Django 2.1.4 on 2019-02-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_commentstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='commentstudent',
            name='parent',
        ),
    ]
