# Generated by Django 2.1.4 on 2019-02-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_commentstudent_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='comments.Comment'),
        ),
    ]
