# Generated by Django 2.1.4 on 2019-01-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login.css')),
                ('Name', models.CharField(max_length=10, verbose_name='Name')),
                ('Surname', models.CharField(max_length=10, verbose_name='Surname')),
                ('username', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('rollno', models.DecimalField(decimal_places=5, max_digits=5)),
                ('phoneno', models.DecimalField(decimal_places=10, max_digits=10)),
                ('password', models.CharField(max_length=10, verbose_name='password')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
