# Generated by Django 2.1.4 on 2019-01-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmpassword',
            field=models.CharField(default=True, max_length=10, verbose_name='Confirm password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rollno',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Roll Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='username'),
        ),
    ]
