# Generated by Django 2.1.4 on 2019-01-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190111_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmpassword',
        ),
    ]
