# Generated by Django 2.1.4 on 2019-01-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_confirmpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
