# Generated by Django 2.1.4 on 2019-01-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190111_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login.css')),
                ('Name', models.CharField(max_length=10, verbose_name='Name')),
                ('Surname', models.CharField(max_length=10, verbose_name='Surname')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('phoneno', models.PositiveSmallIntegerField(unique=True, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=10, verbose_name='password')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
