# Generated by Django 2.1.4 on 2019-01-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_faculty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty',
            new_name='Teacher',
        ),
    ]
