# Generated by Django 2.1.4 on 2019-01-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20190123_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=10, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Surname',
            field=models.CharField(max_length=10, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=10, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneno',
            field=models.PositiveSmallIntegerField(null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.PositiveSmallIntegerField(null=True, unique=True, verbose_name='Roll Number'),
        ),
    ]
