# Generated by Django 2.1.4 on 2019-02-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20190216_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=10, null=True, verbose_name='password'),
        ),
    ]
